# Project: Facebook Ads Campaign Analysis

Objective:
- Understand campaign performance
- Clean the data
- Prepare it for EDA and Machine Learning

In [1]:
import pandas as pd

Load Dataset

In [ ]:
df = pd.read_csv("data\\KAG_conversion_data.csv")

In [5]:
df.head()

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,Impressions,Clicks,Spent,Total_Conversion,Approved_Conversion
0,708746,916,103916,30-34,M,15,7350,1,1.43,2,1
1,708749,916,103917,30-34,M,16,17861,2,1.82,2,0
2,708771,916,103920,30-34,M,20,693,0,0.00,1,0
3,708815,916,103928,30-34,M,28,4259,1,1.25,1,0
4,708818,916,103928,30-34,M,28,4133,1,1.29,1,1

In [6]:
df.tail()

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,Impressions,Clicks,Spent,Total_Conversion,Approved_Conversion
1138,1314410,1178,179977,45-49,F,109,1129773,252,358.189997,13,2
1139,1314411,1178,179978,45-49,F,110,637549,120,173.880003,3,0
1140,1314412,1178,179979,45-49,F,111,151531,28,40.289999,2,0
1141,1314414,1178,179981,45-49,F,113,790253,135,198.710001,8,2
1142,1314415,1178,179982,45-49,F,114,513161,114,165.609999,5,2

Dateset information

In [7]:
df.shape

(1143, 11)

In [10]:
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows : 1143
Columns : 11

In [11]:
df.columns

Index(['ad_id', 'xyz_campaign_id', 'fb_campaign_id', 'age', 'gender',
       'interest', 'Impressions', 'Clicks', 'Spent', 'Total_Conversion',
       'Approved_Conversion'],
      dtype='object')

In [12]:
df.dtypes

ad_id                    int64
xyz_campaign_id          int64
fb_campaign_id           int64
age                     object
gender                  object
interest                 int64
Impressions              int64
Clicks                   int64
Spent                  float64
Total_Conversion         int64
Approved_Conversion      int64
dtype: object

Basic Stastistics

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ad_id,1143.0,987261.130359,193992.814738,708746.0,777632.50,1121185.00,1121804.500,1.314415e+06
xyz_campaign_id,1143.0,1067.382327,121.629393,916.0,936.00,1178.00,1178.000,1.178000e+03
fb_campaign_id,1143.0,133783.989501,20500.308622,103916.0,115716.00,144549.00,144657.500,1.799820e+05
interest,1143.0,32.766404,26.952131,2.0,16.00,25.00,31.000,1.140000e+02
Impressions,1143.0,186732.132983,312762.183208,87.0,6503.50,51509.00,221769.000,3.052003e+06
Clicks,1143.0,33.390201,56.892438,0.0,1.00,8.00,37.500,4.210000e+02
Spent,1143.0,51.360656,86.908418,0.0,1.48,12.37,60.025,6.399500e+02
Total_Conversion,1143.0,2.855643,4.483593,0.0,1.00,1.00,3.000,6.000000e+01
Approved_Conversion,1143.0,0.944007,1.737708,0.0,0.00,1.00,1.000,2.100000e+01

In [18]:
df.describe(include = 'object').T

       count unique    top freq
age     1143      4  30-34  426
gender  1143      2      M  592

Check missing values

In [19]:
df.isnull().sum()

ad_id                  0
xyz_campaign_id        0
fb_campaign_id         0
age                    0
gender                 0
interest               0
Impressions            0
Clicks                 0
Spent                  0
Total_Conversion       0
Approved_Conversion    0
dtype: int64

Check Duplicate records

In [21]:
df.duplicated().sum()

0

Check unique values

In [23]:
df.nunique()

ad_id                  1143
xyz_campaign_id           3
fb_campaign_id          691
age                       4
gender                    2
interest                 40
Impressions            1130
Clicks                  183
Spent                   869
Total_Conversion         32
Approved_Conversion      16
dtype: int64

In [25]:
print(df['age'].nunique())
print(df['gender'].nunique())
print(df['interest'].nunique())

4
2
40

In [26]:
print(df['age'].value_counts())

age
30-34    426
45-49    259
35-39    248
40-44    210
Name: count, dtype: int64

In [27]:
print(df['gender'].value_counts())

gender
M    592
F    551
Name: count, dtype: int64

Rename columns

In [38]:
df = df.rename(columns = {
    'Impressions' : 'impressions',
    'Clicks' : 'clicks',
    'Spent' : 'spent'
})

# convert datatypes

In [39]:
df['age'] = df['age'].astype('category')
df['gender'] = df['gender'].astype('category')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_id                1143 non-null   int64
 1   xyz_campaign_id      1143 non-null   int64
 2   fb_campaign_id       1143 non-null   int64
 3   age                  1143 non-null   category
 4   gender               1143 non-null   category
 5   interest             1143 non-null   int64
 6   impressions          1143 non-null   int64
 7   clicks               1143 non-null   int64
 8   spent                1143 non-null   float64
 9   Total_Conversion     1143 non-null   int64
 10  Approved_Conversion  1143 non-null   int64
dtypes: category(2), float64(1), int64(8)
memory usage: 83.0 KB

# Check invalid values

In [41]:
(df['clicks'] < 0 ).sum()

0

In [42]:
(df['spent'] < 0).sum()

0

In [44]:
(df['Approved_Conversion'] > df['Total_Conversion']).sum()

0

Check memory usage

In [47]:
df.memory_usage(deep = True)

Index                   132
ad_id                  9144
xyz_campaign_id        9144
fb_campaign_id         9144
age                    1531
gender                 1351
interest               9144
impressions            9144
clicks                 9144
spent                  9144
Total_Conversion       9144
Approved_Conversion    9144
dtype: int64

Save Clean Dataset

In [49]:
df.to_csv("data\\cleaned_facebook_ads.csv", index=False)